name: Check process for Thesis-parser
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check:
    runs-on: ubuntu-latest
    name: Check validity of documents
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
          submodules: recursive
      
      - name: Setup Python
        uses: actions/setup-python@v3.1.2
        with:
          python-version: '3.9' 
          cache: 'pip'
          cache-dependency-path: 'Compilator/requirements.txt'
      - name: Setup libraries
        run: pip3 install -r Compilator/requirements.txt
      - name: Run check
        run: python3 main.py -d
  build:
    runs-on: ubuntu-latest
    name: Build process
    needs: [check]
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
          submodules: recursive
      - name: Setup Python
        uses: actions/setup-python@v3.1.2
        with:
          python-version: '3.9'
          cache: 'pip'
          cache-dependency-path: 'Compilator/requirements.txt'
      - name: Setup libraries
        run: pip3 install -r Compilator/requirements.txt
      - name: Run compile
        run: python3 main.py -c
      - name: Cache dist
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: dist/
          key: dist-thesis-${{ github.sha }}
  emanote:
    runs-on: ubuntu-latest   
    needs: [build]
    name: 'Emanote build'
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
          submodules: recursive
      - name: Build FS
        run: |
          mkdir data/
          mkdir data/output/
          mkdir data/dist/
      - name: Uncache dist
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: dist/
          key: dist-thesis-${{ github.sha }}
      - name: Merge data
        run: |
          cp -r dist/* data/dist/
          cp -r -n src/* data/dist/
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: Finished site
          path: data/dist
      - name: Run emanote
        uses: addnab/docker-run-action@v3
        with:
          image: sridca/emanote
          options: -e LANG=C.UTF-8 -e LC_ALL=C.UTF-8 --tmpfs /tmp -v ${{ github.workspace }}/data:/data
          run: emanote -L "/data/dist" gen /data/output
      - name: Upload a Site Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: Finished site
          path: data/output
  pages:
    runs-on: ubuntu-latest
    needs: [emanote]
    name: Upload to GitHub page
    steps:
      - name: Download a Site Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: Finished site
          path: output/
      - name: GitHub Pages
        # You may pin to the exact commit or the version.
        # uses: crazy-max/ghaction-github-pages@a117e4aa1fb4854d021546d2abdfac95be568a3a
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          # GitHub repository where assets will be deployed (default $GITHUB_REPOSITORY)
          repo: ap-thesis.github.io
          # Build directory to deploy
          build_dir: output/
          jekyll: false
          verbose: true